### ISSUE TITLE
Request: Save specific tweet IDs

### ISSUE THREAD

**Issue by DomT4** [mikemcquaid/TwitterDelete#1]
Making a cheeky request for a feature that allows people to not delete specific tweet IDs. Tried coding something myself, but had little progress so far. My Ruby, as we both know, still sucks :cry:. I'll keep reading the Twitter gem documentation and see if I can come up with something that works with the script though.

**Comment by mikemcquaid** [comment]
@DomT4 Good idea. You could add something to https://github.com/mikemcquaid/TwitterDelete/blob/ba9db22bd2f285bd7141d1c0105121e4cee2906d/twitter_delete.rb#L50-L66 to check the ID against a list saved in `.tweets_to_keep` or something? Happy to give you pointers on getting closer.

**Comment by mikemcquaid** [comment]
Passing on this issue in favour of a possible PR later :wink:.
