### ISSUE TITLE
Dies with a vast number of Tweets.

### ISSUE THREAD

**Issue by DomT4** [mikemcquaid/TwitterDelete#2]
Had this happen every time so far. I have a stupidly large number of tweets I want to be rid of, so that's perhaps the cause of the issue. Haven't tried other scripts that use the csv file to delete long-since gone-from-the-maximum-visible-limit tweets, so this might not be entirely the fault of the script. Tried with the system Ruby without luck as well.

I was using another tool before yours', but it couldn't delete past the visible-limit, and it wasn't as up-to-date on the API calls as this one, so I switched.

```
bundle exec ./twitter_delete.rb --user Dom_T4 --csv tweets.csv --force
...

==> Deleting 57439 tweets
/usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/twitter-5.14.0/lib/twitter/rest/request.rb:37:in `rescue in perform': execution expired (Twitter::Error)
	from /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/twitter-5.14.0/lib/twitter/rest/request.rb:32:in `perform'
	from /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/twitter-5.14.0/lib/twitter/rest/utils.rb:51:in `perform_request'
	from /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/twitter-5.14.0/lib/twitter/rest/utils.rb:73:in `perform_request_with_object'
	from /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/twitter-5.14.0/lib/twitter/rest/utils.rb:65:in `perform_post_with_object'
	from /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/twitter-5.14.0/lib/twitter/rest/tweets.rb:100:in `block in destroy_status'
	from /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/twitter-5.14.0/lib/twitter/utils.rb:39:in `block (2 levels) in pmap'
```

**Comment by mikemcquaid** [comment]
@DomT4 In this case I personally retried a few times until it worked. Can you try that? Perhaps I should add an error message suggesting that approach? Thoughts?

**Comment by mikemcquaid** [comment]
Passing on this issue in favour of a possible PR later :wink:.
