### ISSUE TITLE
Support tweet.js

### ISSUE THREAD

**Issue by mooooooooooooooon** [MikeMcQuaid/TwitterDelete#23]
Twitter has started sending a fuller archive, with tweets in a `tweet.js` file instead of `tweets.csv`. It's a plain JS object so probably pretty simple to convert to OpenStruct or even regex it.

**Comment by MikeMcQuaid** [comment]
I’d accept a PR for this!

**Comment by ashleyconnor** [comment]
Hacked something together this afternoon. I ran it against my own account and it appears to work.
