### ISSUE TITLE
Incorrect tweet count

### ISSUE THREAD

**Issue by nirvdrum** [MikeMcQuaid/TwitterDelete#55]
When processing an archive file, TwitterDelete comes up with an incorrect tweet count. I *think* what's happening is tweets from the archive and from the API are being double-counted. The number being reported is approximately 3,000 more than my archive even has.

I'll investigate more, but wanted to file the issue so it wouldn't be lost.

**Comment by MikeMcQuaid** [comment]
Will accept a PR to address this but this isn't something I'm going to chase down myself.

**Comment by nirvdrum** [comment]
No problem. I already planned on tracking it down. I think it's as simple as using a set instead of an array. Did I run afoul of a contribution guideline?

**Comment by MikeMcQuaid** [comment]
> Did I run afoul of a contribution guideline?

No, sorry if I gave that impression! The way I tend to use the issue tracker on GitHub is just for stuff that I or another maintainer plans on working on.

> I already planned on tracking it down. I think it's as simple as using a set instead of an array.

👍 sounds good!
