### ISSUE TITLE
.env file not working

### ISSUE THREAD

**Issue by allisonburtch** [MikeMcQuaid/TwitterDelete#61]
Hi there, thanks for making this open source and sorry this is probably a dumb question. 

I put all my api keys into a file called 'secrets.env' in the twitterdelete folder but when i'm running `./twitter_delete.rb --user irl ` i get `environment variable must be set`

Should my keys be in plaintext or have quotes around them like normal ruby strings? i tried both and neither worked. Some help with implementation would be appreciated. Thanks so much!

**Comment by MikeMcQuaid** [comment]
Needs to be in a file called just `.env`. That work?

**Comment by allisonburtch** [comment]
thanks! that worked!
